
services:

  # ── Ingestion service ───────────────────────────────────────────────────────
  ingestion:
    build: 
      context:
      dockerfile: docker/Dockerfile.ingestion
    env_file: .env

    # Image name 
    image: malaria-ingestion:latest

    
    env_file:
      - .env

  # transformation services
  transformation:
    build:
      context: .
      dockerfile: docker/Dockerfile.transformation
    env_file: .env
   
    depends_on:
      - ingestion  
   # volumes     
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

    restart: "no"